# Generated by Django 2.0 on 2024-03-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=32, verbose_name='用户名')),
                ('Password', models.CharField(max_length=64, verbose_name='密码')),
                ('user_type', models.IntegerField(choices=[(1, '管理员'), (2, '普通用户')], default=2, verbose_name='用户类型')),
            ],
        ),
        migrations.CreateModel(
            name='AssetChangeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField(verbose_name='申请时间')),
                ('NowUnit', models.CharField(max_length=16, verbose_name='现使用单位')),
                ('Applicant', models.CharField(max_length=32, verbose_name='申请人')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDamageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField(verbose_name='申请时间')),
                ('LiftYears', models.IntegerField(verbose_name='使用年限')),
                ('Depreciation_price', models.IntegerField(verbose_name='折旧价格')),
            ],
        ),
        migrations.CreateModel(
            name='AssetMaintainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField(verbose_name='申请时间')),
                ('Applicant', models.CharField(max_length=32, verbose_name='申请人')),
            ],
        ),
        migrations.CreateModel(
            name='AssetsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registration_number', models.CharField(max_length=64, unique=True, verbose_name='登记编号')),
                ('Model', models.CharField(max_length=16, unique=True, verbose_name='设备型号')),
                ('Name', models.CharField(max_length=16, unique=True, verbose_name='设备名称')),
                ('Unit_price', models.IntegerField(unique=True, verbose_name='单价')),
                ('Applicant', models.CharField(max_length=32, verbose_name='登记人')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=16, unique=True, verbose_name='部门名')),
            ],
        ),
        migrations.CreateModel(
            name='RatioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=64, verbose_name='设备类型')),
                ('Ratio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='预计净残值率')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32, verbose_name='供应商名称')),
                ('Supplier_address', models.CharField(max_length=64, unique=True, verbose_name='供应商地址')),
                ('Phone', models.CharField(max_length=32, verbose_name='供应商电话')),
            ],
        ),
        migrations.AddField(
            model_name='assetsinfo',
            name='BelongTo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='assetsinfo',
            name='Supplier_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Supplier', verbose_name='供应商信息'),
        ),
        migrations.AddField(
            model_name='assetmaintaininfo',
            name='BelongTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Department', verbose_name='申请部门'),
        ),
        migrations.AddField(
            model_name='assetmaintaininfo',
            name='Model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_maintain_model', to='app01.AssetsInfo', to_field='Model', verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='assetmaintaininfo',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_maintain_name', to='app01.AssetsInfo', to_field='Name', verbose_name='设备名称'),
        ),
        migrations.AddField(
            model_name='assetmaintaininfo',
            name='Reg_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_maintain_reg_number', to='app01.AssetsInfo', to_field='Registration_number', verbose_name='登记编号'),
        ),
        migrations.AddField(
            model_name='assetdamageinfo',
            name='Model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_damage_model', to='app01.AssetsInfo', to_field='Model', verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='assetdamageinfo',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_damage_name', to='app01.AssetsInfo', to_field='Name', verbose_name='设备名称'),
        ),
        migrations.AddField(
            model_name='assetdamageinfo',
            name='Price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_damage_price', to='app01.AssetsInfo', to_field='Unit_price', verbose_name='购入单价'),
        ),
        migrations.AddField(
            model_name='assetdamageinfo',
            name='Reg_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_damage_reg_number', to='app01.AssetsInfo', to_field='Registration_number', verbose_name='登记编号'),
        ),
        migrations.AddField(
            model_name='assetdamageinfo',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.RatioInfo', verbose_name='资产类型'),
        ),
        migrations.AddField(
            model_name='assetchangeinfo',
            name='Model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_change_model', to='app01.AssetsInfo', to_field='Model', verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='assetchangeinfo',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_change_name', to='app01.AssetsInfo', to_field='Name', verbose_name='设备名称'),
        ),
        migrations.AddField(
            model_name='assetchangeinfo',
            name='OriginalUnit',
            field=models.ForeignKey(max_length=16, on_delete=django.db.models.deletion.CASCADE, related_name='asset_change_original_unit', to='app01.AssetsInfo', to_field='BelongTo', verbose_name='原使用单位'),
        ),
        migrations.AddField(
            model_name='assetchangeinfo',
            name='Reg_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_change_reg_number', to='app01.AssetsInfo', to_field='Registration_number', verbose_name='登记编号'),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='BelongTo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Department', verbose_name='所属部门'),
        ),
    ]
