# Generated by Django 2.0 on 2024-03-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetchangeinfo',
            name='now_type',
            field=models.IntegerField(choices=[(1, '已确认'), (0, '未确认')], default=0),
        ),
        migrations.AddField(
            model_name='assetdamageinfo',
            name='now_type',
            field=models.IntegerField(choices=[(1, '已确认'), (0, '未确认')], default=0),
        ),
        migrations.AddField(
            model_name='assetmaintaininfo',
            name='now_type',
            field=models.IntegerField(choices=[(1, '已确认'), (0, '未确认')], default=0),
        ),
        migrations.AddField(
            model_name='assetsinfo',
            name='now_type',
            field=models.IntegerField(choices=[(1, '已确认'), (0, '未确认')], default=0),
        ),
    ]
