# Generated by Django 4.2.9 on 2024-03-22 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_admininfo_id_alter_assetchangeinfo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='BelongTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='assetchangeinfo',
            name='Model',
            field=models.CharField(max_length=16, verbose_name='设备型号'),
        ),
        migrations.AlterField(
            model_name='assetchangeinfo',
            name='Name',
            field=models.CharField(max_length=16, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='assetdamageinfo',
            name='Model',
            field=models.CharField(max_length=16, verbose_name='设备型号'),
        ),
        migrations.AlterField(
            model_name='assetdamageinfo',
            name='Name',
            field=models.CharField(max_length=16, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='assetdamageinfo',
            name='Price',
            field=models.IntegerField(verbose_name='购入单价'),
        ),
        migrations.AlterField(
            model_name='assetmaintaininfo',
            name='Model',
            field=models.CharField(max_length=16, verbose_name='设备型号'),
        ),
        migrations.AlterField(
            model_name='assetmaintaininfo',
            name='Name',
            field=models.CharField(max_length=16, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='assetsinfo',
            name='Model',
            field=models.CharField(max_length=16, verbose_name='设备型号'),
        ),
        migrations.AlterField(
            model_name='assetsinfo',
            name='Name',
            field=models.CharField(max_length=16, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='assetsinfo',
            name='Unit_price',
            field=models.IntegerField(verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Supplier_address',
            field=models.CharField(max_length=64, verbose_name='供应商地址'),
        ),
    ]
