# Generated by Django 4.2.9 on 2024-04-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_admininfo_belongto_alter_assetchangeinfo_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetchangeinfo',
            name='OriginalUnit',
            field=models.ForeignKey(max_length=16, on_delete=django.db.models.deletion.CASCADE, related_name='asset_change_original_unit', to='app01.department', verbose_name='原使用单位'),
        ),
        migrations.AlterField(
            model_name='assetsinfo',
            name='BelongTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='所属部门'),
        ),
    ]
