# Generated by Django 4.0.6 on 2024-04-10 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_assetchangeinfo_originalunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaintaininfo',
            name='Reg_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_maintain_reg_number', to='app01.assetsinfo', verbose_name='登记编号'),
        ),
    ]
