# Generated by Django 4.0.6 on 2024-04-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_assetmaintaininfo_reg_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetchangeinfo',
            name='Reg_number',
            field=models.CharField(max_length=64, verbose_name='登记编号'),
        ),
        migrations.AlterField(
            model_name='assetdamageinfo',
            name='Reg_number',
            field=models.CharField(max_length=64, verbose_name='登记编号'),
        ),
        migrations.AlterField(
            model_name='assetmaintaininfo',
            name='Reg_number',
            field=models.CharField(max_length=64, verbose_name='登记编号'),
        ),
    ]
