# Generated by Django 4.0.6 on 2024-04-11 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_assetchangeinfo_reg_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetchangeinfo',
            name='Reg_number',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='app01.assetsinfo', to_field='Registration_number', verbose_name='登记编号'),
        ),
        migrations.AlterField(
            model_name='assetdamageinfo',
            name='Reg_number',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='app01.assetsinfo', to_field='Registration_number', verbose_name='登记编号'),
        ),
        migrations.AlterField(
            model_name='assetmaintaininfo',
            name='Reg_number',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='app01.assetsinfo', to_field='Registration_number', verbose_name='登记编号'),
        ),
    ]
