# Generated by Django 4.0.6 on 2024-04-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_alter_assetchangeinfo_reg_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsinfo',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='已确认状态'),
        ),
    ]
