# Generated by Django 4.0.6 on 2024-04-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_assetsinfo_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetchangeinfo',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='已确认状态'),
        ),
        migrations.AddField(
            model_name='assetdamageinfo',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='已确认状态'),
        ),
        migrations.AddField(
            model_name='assetmaintaininfo',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='已确认状态'),
        ),
    ]
