# Generated by Django 4.0.6 on 2024-04-16 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_alter_assetchangeinfo_nowunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsinfo',
            name='asset_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.ratioinfo', verbose_name='资产类型'),
        ),
    ]
