# Generated by Django 4.0.6 on 2024-04-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_assetsinfo_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdamageinfo',
            name='Depreciation_price',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='折旧价格'),
        ),
        migrations.AlterField(
            model_name='assetdamageinfo',
            name='LiftYears',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='使用年限'),
        ),
    ]
