# Generated by Django 4.0.6 on 2024-04-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_alter_assetdamageinfo_depreciation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdamageinfo',
            name='Price',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='购入单价'),
        ),
        migrations.AlterField(
            model_name='assetsinfo',
            name='Unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='单价'),
        ),
    ]
